apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-08-27T08:36:56Z"
  labels:
    run: nginx
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:run: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:run: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl
    operation: Update
    time: "2020-08-27T08:36:56Z"
  name: nginx
  namespace: default
  resourceVersion: "79683"
  selfLink: /api/v1/namespaces/default/services/nginx
  uid: 4937dc9b-968b-462f-9a06-6987a442c584
spec:
  clusterIP: 10.97.159.173
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30087
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
